version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - python -m pip install --upgrade pip

  build:
    commands:
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt